### PR TITLE
Insure the working directory is the same as the script

### PR DESCRIPTION
**Pull request by pseudocc**
Fixes: #6

### CODE REVIEW

**Comment by mrhpearson** [comment]
Neat solution - looks good to me. Thank you!

@nitinexclusively - any concerns?

**Comment by nitinexclusively** [comment]
@pseudocc Thank you for the contribution and Sorry for my late reply.
I think, you have downloaded package from lenovo website instead of coning using github 
>> u@Mersey-1:~$ tar xf lenovo_wwan_fccunlock_package_release2.tar 
>> u@Mersey-1:~$ sudo lenovo_wwan_fccunlock_package/fcc_unlock_setup.sh 

I would recommend to clone it using github and then try executing script .
For normal users, even with this changes you can see error, if fcc_unlock_script.sh is moved to some other unknown directory.
let me know , if you have any comment.

**Comment by pseudocc** [comment]
### Reply to @nitinexclusively 

> I think, you have downloaded package from lenovo website instead of coning using github

No, it's the package you uploaded to the launchpad.

### Further explanation 

It's not related to the way we get the package, the problem is that you have to `cd` into the directory
to run the setup script.

```bash
$ git clone git@github.com:lenovo/lenovo-wwan-unlock.git
$ # the following command will fail
$ sudo lenovo-wwan-unlock/fcc_unlock_setup.sh
$ # currently the way to install the package
$ cd lenovo-wwan-unlock # cd is required
$ sudo ./fcc_unlock_setup.sh
```

**Comment by nitinexclusively** [comment]
> No, it's the package you uploaded to the launchpad.

Understood now !

> 
> ### Further explanation
> It's not related to the way we get the package, the problem is that you have to `cd` into the directory to run the setup script.


For this changes looks OK to me . Thank you for the contribution !

**Pull request merged**
