### PR TITLE
Ubuntu oem debian

### PR DESCRIPTION
**Pull request by binli**
Add the debian dir to build deb packages on jammy

### CODE REVIEW

**Comment by nitinexclusively** [comment]
Hi @binli 
> I did a rebase, hi @nitinexclusively , currently we seperated two packages for fcc-unlock and sar, may I know where the libmbimtools.so should I put? I didn't find any binary depend on this library, thanks!

It should be **/opt/fcc_lenovo/lib/** directory .
Infact all libraries , need to be placed in this directory . You can refer - https://github.com/lenovo/lenovo-wwan-unlock/blob/ubuntu-oem/fcc_unlock_setup.sh for more details

Thank you !

**Comment by binli** [comment]
yes, I installed it at below two files, I want ask libmbimtools.so used by fcc-unlock or sar? And I will put it into correct package. 

```
$ cat debian/lenovo-fccunlock.install 
#!/usr/bin/dh-exec
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/14c3:4d75
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/8086:7560
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/1eac:1007
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/1eac:100d
debian/mm-hook => /usr/lib/x86_64-linux-gnu/ModemManager/fcc-unlock.d/2c7c:6008
DPR_Fcc_unlock_service /opt/fcc_lenovo/
libmodemauth.so /opt/fcc_lenovo/lib/
debian/lenovo-fccunlock.service /lib/systemd/system/

$ cat debian/lenovo-cfgservice.install
configservice_lenovo /opt/fcc_lenovo/
debian/temp/sar_config_files /opt/fcc_lenovo
libconfigserviceR+.so /opt/fcc_lenovo/lib/
libconfigservice350.so /opt/fcc_lenovo/lib/
lenovo-cfgservice.service /lib/systemd/system/
```

**Comment by nitinexclusively** [comment]
> yes, I installed it at below two files, I want ask libmbimtools.so used by fcc-unlock or sar? And I will put it into correct package.

This is used by both FCC unlock and SAR . 
Reason for not having single binary is that FCC unlock script executed from MM for example ModemManager/fcc-unlock.d/14c3:4d75 only for few sec like 5 sec or 10 sec and then it will kill script and its recommended that MM script should only be used to perform FCC unlock not other functionality. So , if setting SAR config takes more time than it will create an issue .
hence , we have separated it. 

Thanks

**Comment by binli** [comment]
I agree with sperating two tasks, and it's same rule for packaging, we seperated two packges for fccunlock and sar.
But we could not install the same file at two packages, is the libmbimtools.so used by configservice_lenovo and DPR_Fcc_unlock_service at the same time?

**Comment by binli** [comment]
BTW, we didn't install  libmbimtools.so, the wwan fccunlock also passed our test before.

**Comment by nitinexclusively** [comment]
> BTW, we didn't install libmbimtools.so, the wwan fccunlock also passed our test before.

We need libmbimtools.so library for Quectel EM160 , RM520N , EM061-K Modem support. FCC unlock will be called after MM service is initialized after inserting SIM  but SAR config is directly started by systemd. 

Thank you !

**Comment by binli** [comment]
Currently lenovo-fccunlock and lenovo-cfservice use the same modaliases, it would be installed together if it matches the machine BIOS id.

**Comment by binli** [comment]
Put the deb package into https://launchpad.net/~lenovo-oem/+archive/ubuntu/preload

**Comment by nitinexclusively** [comment]
> Put the deb package into https://launchpad.net/~lenovo-oem/+archive/ubuntu/preload

OK , So , how can we test it or will be directly available in OEM image ?  
Below command will not work now, Correct ? We cannot see /opt/fcc_lenovo directory now 
sudo add-apt-repository ppa:lenovo-oem/preload
sudo apt update

Thanks

**Comment by binli** [comment]
Nintin, please wait a while, I will let you know when it's ready, I just found it failed to build last night.

**Pull request merged**
